/* eslint-disable no-console */
/**
 * Auto-detects monochrome black-on-transparent feature-card logos.
 *
 * The product feature cards (FeatureCardsGrid) render every logo on a single
 * dark "glass" tile in BOTH light and dark themes. White / teal / colorful
 * logos read fine on that tile, but pure-black line icons (e.g. refrigerator
 * feature icons, TV depth-enhancer / noise-reduction) would be invisible.
 *
 * Those black icons are black-on-transparent, so the component inverts them to
 * white at render time. This script scans every logo asset and emits the set of
 * paths that need that invert, so we never have to hand-tag them.
 *
 * Run: npm run logos:scan   (re-run whenever logo assets are added/changed)
 */
import { promises as fs } from 'fs';
import path from 'path';
import sharp from 'sharp';

const PUBLIC_DIR = path.join(process.cwd(), 'public');
const PRODUCTS_DIR = path.join(PUBLIC_DIR, 'products');
const OUTPUT_FILE = path.join(process.cwd(), 'content', 'monoFeatureLogos.generated.ts');

const IMAGE_EXT = new Set(['.png', '.webp']); // formats with alpha we can analyze

// Classification thresholds — tuned for the line-icon assets in /products/**/logos.
// NOTE: we use ABSOLUTE chroma (max-min)/255, not relative saturation. Relative
// saturation explodes on near-black pixels (e.g. rgb(1,0,0) → 1.0) and would
// wrongly mark pure-black icons like depth-enhancer as "colorful".
const MIN_TRANSPARENT_FRACTION = 0.25; // icon on transparent bg (skips solid-bg photos)
const MAX_MEAN_CHROMA = 0.12; // not colorful, not the Hisense teal/green
const MAX_MEAN_LUMINANCE = 0.5; // ink is dark overall
const MIN_DARK_INK_FRACTION = 0.6; // most opaque pixels are dark + desaturated

type Classification = {
  key: string;
  mono: boolean;
  meanLum: number;
  meanSat: number;
  transparentFraction: number;
};

async function listLogoFiles(dir: string): Promise<string[]> {
  const out: string[] = [];
  const entries = await fs.readdir(dir, { withFileTypes: true, recursive: true });
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    // Node returns parentPath on the dirent for recursive reads.
    const parent = (entry as unknown as { parentPath?: string; path?: string }).parentPath ?? dir;
    const full = path.join(parent, entry.name);
    if (!full.split(path.sep).includes('logos')) continue;
    if (IMAGE_EXT.has(path.extname(entry.name).toLowerCase())) out.push(full);
  }
  return out;
}

async function classify(file: string): Promise<Classification> {
  const rel = path.relative(PRODUCTS_DIR, file).split(path.sep).join('/');
  const { data, info } = await sharp(file)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const channels = info.channels; // 4 after ensureAlpha
  const total = info.width * info.height;
  let opaque = 0;
  let transparent = 0;
  let sumLum = 0;
  let sumChroma = 0;
  let darkInk = 0;

  for (let i = 0; i < data.length; i += channels) {
    const a = data[i + 3];
    if (a < 24) {
      transparent++;
      continue;
    }
    if (a < 128) continue; // ignore soft anti-alias fringe in the stats
    const r = data[i];
    const g = data[i + 1];
    const b = data[i + 2];
    const max = Math.max(r, g, b);
    const min = Math.min(r, g, b);
    const lum = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
    const chroma = (max - min) / 255; // absolute, stable at low luminance
    sumLum += lum;
    sumChroma += chroma;
    if (lum < 0.55 && chroma < 0.12) darkInk++;
    opaque++;
  }

  const meanLum = opaque ? sumLum / opaque : 1;
  const meanChroma = opaque ? sumChroma / opaque : 1;
  const transparentFraction = total ? transparent / total : 0;
  const darkInkFraction = opaque ? darkInk / opaque : 0;

  const mono =
    opaque > 0 &&
    transparentFraction >= MIN_TRANSPARENT_FRACTION &&
    meanChroma <= MAX_MEAN_CHROMA &&
    meanLum <= MAX_MEAN_LUMINANCE &&
    darkInkFraction >= MIN_DARK_INK_FRACTION;

  return { key: rel, mono, meanLum, meanSat: meanChroma, transparentFraction };
}

async function main() {
  const files = await listLogoFiles(PRODUCTS_DIR);
  files.sort();
  const results: Classification[] = [];
  for (const file of files) {
    try {
      results.push(await classify(file));
    } catch (err) {
      console.warn(`! skipped ${file}: ${(err as Error).message}`);
    }
  }

  const mono = results.filter((r) => r.mono).map((r) => r.key);
  mono.sort();

  const banner =
    '// AUTO-GENERATED by scripts/detect-mono-logos.ts — do not edit by hand.\n' +
    '// Black-on-transparent feature-card logos that are inverted to white on the\n' +
    '// dark feature-card tile. Re-run `npm run logos:scan` after changing logo assets.\n\n';
  const body =
    'export const MONO_FEATURE_LOGOS = new Set<string>([\n' +
    mono.map((k) => `  '${k}',`).join('\n') +
    (mono.length ? '\n' : '') +
    ']);\n';

  await fs.writeFile(OUTPUT_FILE, banner + body, 'utf8');

  console.log(`Scanned ${results.length} logo assets → ${mono.length} flagged for invert.`);
  console.log(`Wrote ${path.relative(process.cwd(), OUTPUT_FILE)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
